export const dbObject = {
  segments: [
    {
      id: "q7Vd5qC6",
      videoId: "t-LsjB45tOg",
      from: 31460,
      to: 36980,
      text: "Donc j'ai réfléchi sur le sujet et j'ai trouvé 4 critères,",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "7F7_nIOo",
      videoId: "t-LsjB45tOg",
      from: 42260,
      to: 45680,
      text: "Et donc on commence avec le premier critère qui est :",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "L4AWJ7z4",
      videoId: "t-LsjB45tOg",
      from: 76000,
      to: 79400,
      text: "Quand je parle rapidement je dirai : j'peux v'nir c'soir ?",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "mqcRd-ms",
      videoId: "t-LsjB45tOg",
      from: 251840,
      to: 254400,
      text: "Un garçon : un gars.",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "asdfcRd-ms",
      videoId: "B9rVdOLWsak",
      from: 688500,
      to: 690200,
      text: "Et une dernière chose avant de finir",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "fqcfd-ms",
      rating: 5,
      videoId: "B9rVdOLWsak",
      from: 690200,
      to: 694200,
      text: "C'est normal d'avoir des jours avec et des jours sans",
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "oTxl4RSL",
      videoId: "t-LsjB45tOg",
      from: 281260,
      to: 291020,
      text: "Ciné pour Cinéma, pub pour publicité, d'acc pour d'accord, la fac pour la faculté ou l'université.",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "N1FlGRt-",
      videoId: "t-LsjB45tOg",
      from: 328520,
      to: 329580,
      text: "On va dire ON.",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "Y2H70Ivg",
      videoId: "t-LsjB45tOg",
      from: 342780,
      to: 347140,
      text: "C'est trop formel, donc à l'écrit ça va, dans un contexte plus soutenu ça va.",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "KEC5hO6T",
      videoId: "t-LsjB45tOg",
      from: 401800,
      to: 406100,
      text: "Mais pour quelqu'un qui a 25 ans ça va peut-être être celui des moins de 20 ans.",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "nUOsfdXf",
      videoId: "t-LsjB45tOg",
      from: 517600,
      to: 519680,
      text: "Chelou pour louche.",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "8cEB5lJC",
      videoId: "t-LsjB45tOg",
      from: 572880,
      to: 577560,
      text: "Et finalement, le quatrième critère pour parler comme les Français :",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "I_hd0hUY",
      videoId: "t-LsjB45tOg",
      from: 671280,
      to: 673540,
      text: "Volontairement ou involontairement.",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "qNqOLB4J",
      videoId: "t-LsjB45tOg",
      from: 821760,
      to: 822960,
      text: "Voilà ! ^^",
      rating: 5,
      channel: {
        channelId: "UCVJJy6MLOtSJQebC86L7SDw",
        channelTitle: "Julie Alors learn French",
      },
    },
    {
      id: "MC9uL6te",
      videoId: "v1R5QR1onU4",
      from: 76380,
      to: 79340,
      text: "Déjà, il faut mémoriser du vocabulaire",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "kCoIdUi6",
      videoId: "v1R5QR1onU4",
      from: 547960,
      to: 550780,
      text: "essayez de les utiliser\ndans une conversation",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "9WJOfvl8",
      videoId: "v1R5QR1onU4",
      from: 611680,
      to: 614980,
      text: "La dernière chose que je voudrais vous dire\navant de finir cette vidéo",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "THTXmW8B",
      videoId: "v1R5QR1onU4",
      from: 649000,
      to: 652120,
      text: "vous essayez juste de communiquer\navec des francophones",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "MXvzx_yn",
      videoId: "v1R5QR1onU4",
      from: 678160,
      to: 682160,
      text: "et si cette personne me comprend bien,\nme comprend sans difficulté",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "4eyysVyS",
      videoId: "oTKWwVrCrI8",
      from: 13626,
      to: 15655,
      text: "c'était ma question preferée",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "TvBi0ow9",
      videoId: "oTKWwVrCrI8",
      from: 513865,
      to: 516079,
      text: "Tu n'as pas grand-chose à perdre",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "k6o9drZB",
      videoId: "hfdvXiazsVA",
      from: 95800,
      to: 97320,
      text: "J'avais une opportunité",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "1dQzsxl6",
      videoId: "hfdvXiazsVA",
      from: 555260,
      to: 557360,
      text: "pour les végétariens\net les vegans",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "DndWtw1n",
      videoId: "hfdvXiazsVA",
      from: 668340,
      to: 670340,
      text: "C'est un parc qui est\nsur plusieurs niveaux",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "iVPhOPMH",
      videoId: "T5hbFlMD1MA",
      from: 373070,
      to: 378940,
      text: "Donc, cherche le positif dans le fait que\ncertaines personnes se moquent.",
      rating: 5,
      channel: {
        channelId: "UCQpM25U6iqaRSO-SZxd5oDw",
        channelTitle: "Français Authentique",
      },
    },
    {
      id: "Ri6sGr71",
      videoId: "UWkyyhxPiiw",
      from: 87800,
      to: 91800,
      text: "Ici, plus de 400 policiers sont mobilisés de jour comme de nuit",
      rating: 5,
      channel: {
        channelId: "UCAJM0dH9j5xv6Uu94Mu5REQ",
        channelTitle: "SPICA LIFE",
      },
    },
    {
      id: "BYmV0ErD",
      videoId: "UWkyyhxPiiw",
      from: 91800,
      to: 94567,
      text: "Pour répondre à cette augmentation spectaculaire.",
      rating: 5,
      channel: {
        channelId: "UCAJM0dH9j5xv6Uu94Mu5REQ",
        channelTitle: "SPICA LIFE",
      },
    },
    {
      id: "poPeC7Gb",
      videoId: "UWkyyhxPiiw",
      from: 106280,
      to: 110000,
      text: "Des actes qui conduisent parfois à la mort des victimes,",
      rating: 5,
      channel: {
        channelId: "UCAJM0dH9j5xv6Uu94Mu5REQ",
        channelTitle: "SPICA LIFE",
      },
    },
    {
      id: "suS8mjM8",
      videoId: "M2_tmKz3gBI",
      from: 65020,
      to: 66010,
      text: "Mais pas tout le temps.",
      rating: 5,
      channel: {
        channelId: "UCPHJfLg1VeNBsfzzTszpmmQ",
        channelTitle: "Montreux Comedy",
      },
    },
    {
      id: "WFWr2WJB",
      videoId: "M2_tmKz3gBI",
      from: 71220,
      to: 72640,
      text: "Je (ne) suis pas\nune femme par exemple.",
      rating: 5,
      channel: {
        channelId: "UCPHJfLg1VeNBsfzzTszpmmQ",
        channelTitle: "Montreux Comedy",
      },
    },
    {
      id: "mYM0iusd",
      videoId: "M2_tmKz3gBI",
      from: 111040,
      to: 113980,
      text: "On est triste un peu avant les règles et pendant les règles.",
      rating: 5,
      channel: {
        channelId: "UCPHJfLg1VeNBsfzzTszpmmQ",
        channelTitle: "Montreux Comedy",
      },
    },
    {
      id: "1DzlFgey",
      videoId: "ud91woekqMM",
      from: 278800,
      to: 281380,
      text: "La position géographique\nde cette région",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "cjIM2h0L",
      videoId: "ud91woekqMM",
      from: 534320,
      to: 538000,
      text: "Une fois que cette institution est créée",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "rXN9xFZl",
      videoId: "ud91woekqMM",
      from: 561580,
      to: 564540,
      text: "Quand on analyse un peu\ncette évolution",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "_g6ztCYu",
      videoId: "ud91woekqMM",
      from: 604320,
      to: 610000,
      text: "Et ce qui est intéressant, c'est que\nl'accent est devenu un facteur de discrimination",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "1j7qi87p",
      videoId: "ud91woekqMM",
      from: 687740,
      to: 689700,
      text: "les institutions culturelles",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "nrUCpkMt",
      videoId: "ud91woekqMM",
      from: 810720,
      to: 813460,
      text: "qui a inventé un terme pour ça",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "a_VGV_Mg",
      videoId: "ud91woekqMM",
      from: 815580,
      to: 819800,
      text: "La glottophobie, c'est une forme\nde discrimination négative",
      rating: 5,
      channel: {
        channelId: "UCI4xp8qHD1MDErkqxb1dPbA",
        channelTitle: "innerFrench",
      },
    },
    {
      id: "1ffdujf1",
      videoId: "K_QKabwLlds",
      from: 66200,
      to: 71000,
      text: "Je profite toujours de ces moments pour apprends de nouvelles choses",
      rating: 5,
      channel: {
        channelId: "UCQpM25U6iqaRSO-SZxd5oDw",
        channelTitle: "Français Authentique",
      },
    },
    {
      id: "1ffdujf2",
      videoId: "K_QKabwLlds",
      from: 79000,
      to: 81000,
      text: "J'ai une excellente nouvelle",
      rating: 5,
      channel: {
        channelId: "UCQpM25U6iqaRSO-SZxd5oDw",
        channelTitle: "Français Authentique",
      },
    },
    {
      id: "1ffdujf3",
      videoId: "K_QKabwLlds",
      from: 119500,
      to: 124000,
      text: "Cette promotion n'est valable que jusqu'au 27 décembre",
      rating: 5,
      channel: {
        channelId: "UCQpM25U6iqaRSO-SZxd5oDw",
        channelTitle: "Français Authentique",
      },
    },
    {
      id: "2ffdujf1",
      videoId: "5CbRL60hHi4",
      from: 24500,
      to: 26500,
      text: "Et ça, ça m'a fait un petit coup",
      rating: 5,
      channel: {
        channelId: "UCQOR99glA-qqvPHr0KUqyWA",
        channelTitle: "AlloCiné - Interviews",
      },
    },
    {
      id: "2ffdujf2",
      videoId: "5CbRL60hHi4",
      from: 66800,
      to: 68600,
      text: "Tout le monde était très heureux",
      rating: 5,
      channel: {
        channelId: "UCQOR99glA-qqvPHr0KUqyWA",
        channelTitle: "AlloCiné - Interviews",
      },
    },
    {
      id: "2ffdujf3",
      videoId: "5CbRL60hHi4",
      from: 116200,
      to: 117800,
      text: "Elle (n')est pas du tout comme ça",
      rating: 5,
      channel: {
        channelId: "UCQOR99glA-qqvPHr0KUqyWA",
        channelTitle: "AlloCiné - Interviews",
      },
    },
    {
      id: "3ffdujf1",
      videoId: "oB5Vaq2dsEc",
      from: 0,
      to: 2700,
      text: "Bienvenue à Paris dans le onzième arrondissement",
      rating: 5,
      channel: {
        channelId: "UCmHfCD8c8CmjlyWa8d4GObg",
        channelTitle: "Clique TV",
      },
    },
    {
      id: "3ffdujf2",
      videoId: "oB5Vaq2dsEc",
      from: 86500,
      to: 88000,
      text: "Il sort avec deux filles en même temps?",
      rating: 5,
      channel: {
        channelId: "UCmHfCD8c8CmjlyWa8d4GObg",
        channelTitle: "Clique TV",
      },
    },
    {
      id: "3ffdujf3",
      videoId: "oB5Vaq2dsEc",
      from: 157500,
      to: 162300,
      text: "Cette relation deviendra une amitié basée sur l'amour de la cascade?",
      rating: 5,
      channel: {
        channelId: "UCmHfCD8c8CmjlyWa8d4GObg",
        channelTitle: "Clique TV",
      },
    },
  ],
};
